# Generated by Django 3.0.4 on 2020-03-21 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreUsuario', models.CharField(default='', max_length=30, unique=True)),
                ('contrasenia', models.CharField(default='', max_length=30)),
                ('telefono', models.IntegerField(verbose_name=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Licencia',
            fields=[
                ('idLicencia', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombrePais', models.CharField(
                    choices=[('UY', 'Uruguay'), ('AR', 'Argentina'), ('BR', 'Brasil'), ('CL', 'Chile'),
                             ('BO', 'Bolivia'), ('CO', 'Colombia'), ('EC', 'Ecuador'), ('PY', 'Paraguay'),
                             ('PE', 'Perú'), ('VE', 'Venezuela')], default='UY', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroAlquiler',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('marca', models.CharField(default='', max_length=15)),
                ('anio', models.IntegerField(default=1900)),
                ('categoria', models.CharField(
                    choices=[('auto', 'Auto'), ('camioneta', 'Camioneta'), ('camion', 'Camion'), ('moto', 'Moto')],
                    default='auto', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='VehiculoPapeles',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cracAPP.Vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('ci', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreUsuario', models.CharField(default='', max_length=30, unique=True)),
                ('contrasenia', models.CharField(default='', max_length=30)),
                ('nombre', models.CharField(max_length=15)),
                ('apellido', models.CharField(max_length=15)),
                ('fechaNacimiento', models.DateField()),
                ('correoElectronico', models.CharField(max_length=50)),
                ('calle', models.CharField(max_length=50)),
                ('esquina', models.CharField(max_length=50)),
                ('numDireccion', models.IntegerField(verbose_name=4)),
                ('bizz', models.IntegerField(verbose_name=4)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cracAPP.Ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudRegistro',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nroSolicitud', models.IntegerField()),
                ('estadoSolicitud',
                 models.CharField(choices=[('PEN', 'Pendiente'), ('APR', 'Aprobada'), ('DEN', 'Denegada')],
                                  default='PEN', max_length=3)),
                ('fechaSolicitud', models.DateField()),
                ('horaSolicitud', models.TimeField()),
                ('fechaGestion', models.DateField()),
                ('horaGestion', models.TimeField()),
                ('comentarioAprobador', models.CharField(max_length=100)),
                ('aprobador',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cracAPP.Administrador')),
                ('ciSolicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cracAPP.Usuario')),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cracAPP.Ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudAlquiler',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('usario_solicitante',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cracAPP.Usuario')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cracAPP.Vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilRenta',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cracAPP.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilAlquila',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cracAPP.Usuario')),
                ('libreta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cracAPP.Licencia')),
            ],
        ),
        migrations.AddField(
            model_name='licencia',
            name='conductor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cracAPP.Usuario'),
        ),
        migrations.CreateModel(
            name='Denegacion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('numeroSolicitud', models.IntegerField()),
                ('comentarioDenegacion', models.CharField(max_length=100)),
                ('administradorDenegador',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cracAPP.Administrador')),
                ('ciSolicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cracAPP.Usuario')),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cracAPP.Ciudad')),
            ],
        ),
        migrations.AddField(
            model_name='ciudad',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cracAPP.Pais'),
        ),
    ]
