# Generated by Django 3.0.4 on 2020-03-14 04:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cracAPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
