# Generated by Django 3.0.4 on 2020-03-29 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alquiler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroalquiler',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='solicitudalquiler',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
