# Generated by Django 3.0.4 on 2020-03-24 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreUsuario', models.CharField(default='', max_length=30, unique=True)),
                ('contrasenia', models.CharField(default='', max_length=30)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('mail', models.EmailField(default='', max_length=50, unique=True)),
                ('telefono', models.IntegerField(verbose_name=20)),
                ('antiguedad', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ciudad', models.CharField(max_length=30)),
                ('pais', models.CharField(choices=[('UY', 'Uruguay'), ('AR', 'Argentina'), ('BR', 'Brasil'), ('CL', 'Chile'), ('BO', 'Bolivia'), ('CO', 'Colombia'), ('EC', 'Ecuador'), ('PY', 'Paraguay'), ('PE', 'Perú'), ('VE', 'Venezuela')], default='UY', max_length=2)),
            ],
            options={
                'unique_together': {('ciudad', 'pais')},
            },
        ),
        migrations.CreateModel(
            name='Licencia',
            fields=[
                ('idLicencia', models.IntegerField(primary_key=True, serialize=False)),
                ('catA', models.BooleanField(default=False)),
                ('catB', models.BooleanField(default=False)),
                ('catC', models.BooleanField(default=False)),
                ('catD', models.BooleanField(default=False)),
                ('catE', models.BooleanField(default=False)),
                ('catF', models.BooleanField(default=False)),
                ('catG1', models.BooleanField(default=False)),
                ('catG2', models.BooleanField(default=False)),
                ('catG3', models.BooleanField(default=False)),
                ('catH', models.BooleanField(default=False)),
                ('vencimiento', models.DateField()),
                ('restricciones', models.IntegerField(verbose_name=2)),
                ('observaciones', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('ci', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreUsuario', models.CharField(max_length=30, unique=True)),
                ('contrasenia', models.CharField(max_length=30)),
                ('mail', models.EmailField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('telefono', models.IntegerField(verbose_name=20)),
                ('fechaNacimiento', models.DateField()),
                ('calle', models.CharField(max_length=50)),
                ('esquina', models.CharField(max_length=50)),
                ('numDireccion', models.IntegerField(verbose_name=4)),
                ('bizz', models.IntegerField(verbose_name=4)),
                ('antiguedad', models.DateField(auto_now_add=True)),
                ('ciudad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.Ciudad', verbose_name='Ciudad')),
            ],
            options={
                'unique_together': {('nombre', 'apellido')},
            },
        ),
        migrations.CreateModel(
            name='SolicitudRegistro',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nroSolicitud', models.IntegerField()),
                ('estadoSolicitud', models.CharField(choices=[('PEN', 'Pendiente'), ('APR', 'Aprobada'), ('DEN', 'Denegada')], default='PEN', max_length=3)),
                ('fechaSolicitud', models.DateField()),
                ('horaSolicitud', models.TimeField()),
                ('fechaGestion', models.DateField()),
                ('horaGestion', models.TimeField()),
                ('comentarioAprobador', models.CharField(max_length=100)),
                ('aprobador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Administrador')),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Ciudad')),
                ('usuarioSolicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilPropietario',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cuenta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuario.Usuario')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.SolicitudRegistro')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilAlquila',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cuenta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuario.Usuario')),
                ('libreta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuario.Licencia')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.SolicitudRegistro')),
            ],
        ),
        migrations.AddField(
            model_name='licencia',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuario.Usuario'),
        ),
        migrations.CreateModel(
            name='Denegacion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('comentarioDenegacion', models.CharField(max_length=100)),
                ('fechaDenegacion', models.DateTimeField(auto_now_add=True)),
                ('administradorDenegador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Administrador')),
                ('ciSolicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Usuario')),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Ciudad')),
            ],
        ),
        migrations.AddField(
            model_name='administrador',
            name='ciudad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.Ciudad', verbose_name='Ciudad'),
        ),
    ]
