# Generated by Django 3.0.3 on 2020-04-07 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0003_auto_20200406_2201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('carRegistration', models.CharField(max_length=12, unique=True)),
                ('brand', models.CharField(max_length=20)),
                ('carModel', models.CharField(max_length=15)),
                ('year', models.IntegerField(blank=True, default=1900)),
                ('seatsNumber', models.IntegerField(blank=True, verbose_name=2)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Profile', verbose_name='Propietario')),
            ],
            options={
                'ordering': ['carRegistration'],
            },
        ),
    ]
