# Generated by Django 3.0.3 on 2020-04-08 02:30

from django.db import migrations, models
import django.db.models.deletion
import registration.models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20200406_2201'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vechicle_Publication',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('carPhoto', models.ImageField(blank=True, null=True, upload_to=registration.models.custom_upload_to)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Profile', verbose_name='Propietario')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.Vehicle', verbose_name='Vehiculo')),
            ],
        ),
    ]
