# Generated by Django 3.0.4 on 2020-03-24 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('matricula', models.CharField(max_length=12, unique=True)),
                ('marca', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=15)),
                ('anio', models.IntegerField(blank=True, default=1900)),
                ('asientos', models.IntegerField(blank=True, verbose_name=2)),
                ('puertas', models.IntegerField(blank=True, verbose_name=2)),
                ('categoria', models.CharField(choices=[('auto', 'Auto'), ('camioneta', 'Camioneta'), ('camion', 'Camion'), ('moto', 'Moto')], default='auto', max_length=15)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.PerfilPropietario', verbose_name='Propietario')),
            ],
        ),
        migrations.CreateModel(
            name='VehiculoPapeles',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('documentacion', models.CharField(max_length=200)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculo.Vehiculo', verbose_name='Vehiculo')),
            ],
        ),
    ]
